### ISSUE TITLE
在操作页面，我的资源，上传资源的时候，提示添加失败，无法将资源注册到数据集中

### ISSUE THREAD

**Issue by mengxiangyu-png** [primihub/primihub-platform#105]
您好，我在操作页面，我的资源，上传资源的时候，提示添加失败，无法将资源注册到数据集中，这个错是哪里出了问题，我在哪里可以看详细日志。
![内网通截图20230414120935](https://user-images.githubusercontent.com/57181576/231945680-7353ef00-ceed-4703-a69f-a8a6861cbe0a.png)

**Comment by fuxingbit** [comment]
![image](https://user-images.githubusercontent.com/26339492/231952316-17a521ce-9d09-45aa-98e4-f32fa079f563.png)

**Comment by fuxingbit** [comment]
docker logs -f application1
docker logs -f primihub-node0 
看日志
