### ISSUE TITLE
我用idea打开后端代码后提示，找不到符号，没有这个方法。

### ISSUE THREAD

**Issue by mengxiangyu-png** [primihub/primihub-platform#110]
![image](https://user-images.githubusercontent.com/57181576/232218579-4576c8b5-345f-4841-b52d-83103e591c0e.png)
WorkerGrpcClientSpringTest.java

+.setJobId(ByteString.copyFrom("1".getBytes(StandardCharsets.UTF_8)))

**Comment by likehabits** [comment]
Please pull the latest development branch
