### ISSUE TITLE
匿综查询，选择多个资源后，结果不一致

### ISSUE THREAD

**Issue by mengxiangyu-png** [primihub/primihub-platform#116]
匿综查询，选择多个资源后，似乎只对第一个资源的关键字进行了匹配
![image](https://user-images.githubusercontent.com/57181576/236990226-b8653e8b-39a8-4ebf-afe1-86ab489d52bc.png)

**Comment by leiyannan** [comment]
目前开源版本只支持查询一个资源，默认是第一个
