### ISSUE TITLE
隐私求交的KKRT算法报错

### ISSUE THREAD

**Issue by mengxiangyu-png** [primihub/primihub-platform#117]
![image](https://user-images.githubusercontent.com/57181576/237008515-930f83f2-707e-4678-932a-b232d1ee95cc.png)
页面中隐私求交的kkrt做法，求交集时候失败

**Comment by leiyannan** [comment]
当资源中重复数据过多时，建议使用ECDH协议

**Comment by phoenix20162016** [comment]
当前最新版本无法复现出现的问题，请在最新版本中重新试用，有问题请提供下相关日志，谢谢

**Comment by phoenix20162016** [comment]
暂未收到关于该问题的后续反馈，close
