### ISSUE TITLE
匿踪查询和联邦学习不支持使用从数据库导入的资源

### ISSUE THREAD

**Issue by LindaHu0701** [primihub/primihub-platform#118]

**Comment by xuefeng-xu** [comment]
@LindaHu0701 你好，暂不支持

**Comment by xuefeng-xu** [comment]
@LindaHu0701 你好，联邦学习已支持mysql数据库

**Comment by phoenix20162016** [comment]
PIR支持了数据库作为数据源，欢迎试用，使用最新的dev分支即可

**Comment by xuefeng-xu** [comment]
1.6.8均已支持
https://github.com/primihub/primihub/releases/tag/1.6.8
