### ISSUE TITLE
匿踪查询只能在第一列中查询

### ISSUE THREAD

**Issue by LindaHu0701** [primihub/primihub-platform#119]
例如，官方提供的测试数据“PIR-PSI用户数据A”中，包括姓名和年龄两列，查询某个姓名可以查到，查询“男”或“女”无法查到

**Comment by LindaHu0701** [comment]
例如，官方提供的测试数据“PIR-PSI用户数据A”中，包括姓名和年龄两列，查询某个姓名可以查到，查询“男”或“女”无法查到

**Comment by phoenix20162016** [comment]
当前只支持第一列作为查询条件，后面的数据作为value返回的形式，后续会逐步会以灵活配置形式支持
