### ISSUE TITLE
界面上总弹出time out的错误提示框，但不影响平台的使用

### ISSUE THREAD

**Issue by LindaHu0701** [primihub/primihub-platform#123]
日志报错：
I/O error on GET request for "https://node1.primihub.com/collect/operate/getNodeList": Connect to node1.primihub.com:443 [node1.primihub.com/118.190.39.100] failed: connect timed out; nested exception is org.apache.http.conn.ConnectTimeoutException: Connect to node1.primihub.com:443 [node1.primihub.com/118.190.39.100] failed: connect timed out

**Comment by fuxingbit** [comment]
你说的界面是终端的日志界面还是浏览器的操作界面？
这个接口的作用是上报节点的位置到整个隐私计算网络，设计是只上报一次，如果无网等原因上报不成功不会重复上报，具体我们查一下

**Comment by LindaHu0701** [comment]
我使用“docker logs -f application2”这个命令查到的

**Comment by LindaHu0701** [comment]
浏览器的控制台的报错是：
Uncaught (in promise) Error: timeout of 20000ms exceeded
    at t.exports (chunk-libs.780b8709.js:12:14940)
    at XMLHttpRequest.p.ontimeout (chunk-libs.780b8709.js:77:5295)

**Comment by likehabits** [comment]
1.6.6 版本该问题已解决
