### ISSUE TITLE
添加节点信息超时，刷新之后界面已经添加上了

### ISSUE THREAD

**Issue by LindaHu0701** [primihub/primihub-platform#135]
**bug描述**
添加节点信息报超时的错误，刷新之后界面已经添加上了

**复现步骤**
 添加机构A，网关地址为http://改该节点机器的IP:30811/prod-api和http://gateway0:8080都会这样

**bug日志**
无报错

**环境（请填写完整）:**
- OS: Linux
- Arch: x86_64
- 部署方式: docker
- PrimiHub版本: 1.6.6

**Comment by likehabits** [comment]
您好,我们未能复现出您说的这种情况。
请描述或截图等方式说明一下如何出现这种情况的流程，我们进行复现出来会立即修复该问题。

**Comment by fuxingbit** [comment]
你部署的机器是什么系统？
