### ISSUE TITLE
添加合作节点时可以添加自己，显示”对方正在审核中“，且无法删除

### ISSUE THREAD

**Issue by LindaHu0701** [primihub/primihub-platform#136]
**bug描述**
添加合作节点时可以添加自己，显示”对方正在审核中“，且无法删除，建议设置为不允许添加自己

**环境（请填写完整）:**
- OS: Linux
- Arch: x86_64
- 部署方式: docker
- PrimiHub版本: 如1.6.6

**Comment by likehabits** [comment]
已收录该建议，在下个1.6.7版本中实现
您也可以直接拉去1.6.7分支进行使用，但该分支不是稳定的
