### ISSUE TITLE
增加隐匿查询结束任务和删除任务功能

### ISSUE THREAD

**Issue by LindaHu0701** [primihub/primihub-platform#137]
**功能描述**
建议增加隐匿查询结束任务和删除任务功能
-

**动机描述**
有时候隐匿查询进行了很长时间还没有成功或者失败，占用内存，影响其它任务的进行
-

**其他**
可以参考横向/纵向任务的取消任务功能和隐私求交任务的删除任务功能
-

**Comment by phoenix20162016** [comment]
任务是支持从客户端发送结束任务的命令的，但是后端杀死任务是一个异步的流程，是在每个操纵步骤执行前后之后进行判断的，对于某个流程中暂不支持

**Comment by simongong** [comment]
@LindaHu0701 是说在管理界面上支持删除操作吗？

**Comment by LindaHu0701** [comment]
是的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月11日(周五) 上午10:04
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [primihub/primihub-platform] 增加隐匿查询结束任务和删除任务功能 (Issue #137)




 
@LindaHu0701 是说在管理界面上支持删除操作吗？

**Comment by simongong** [comment]
可以支持，我们排到后面的产品规划里。

**Comment by phoenix20162016** [comment]
@LindaHu0701  1.6.10已支持，欢迎试用
