### ISSUE TITLE
增加隐匿查询过程日志的打印

### ISSUE THREAD

**Issue by LindaHu0701** [primihub/primihub-platform#138]
**功能描述**
希望增加隐匿查询过程日志的打印
-

**动机描述**
数据量较大时，隐匿查询进行很长时间，在这个过程中不知道发生了什么
-

**其他**
参考联合建模的日志量，增加隐匿查询进行过程中的日志
-

**Comment by phoenix20162016** [comment]
日志的显示可以通过设置日志级别实现的，在节点启动时候设置
export GLOG_logtostderr=1 GLOG_v=${log_level}
具体可以参考start_server.sh脚本
用docker启动的话需要修改下在docker compose中设置

**Comment by LindaHu0701** [comment]
请问如果用docker启动，要修改docker compose中的哪个设置

**Comment by fuxingbit** [comment]
![image](https://github.com/primihub/primihub-platform/assets/26339492/1a0a8786-79ad-4d57-bca3-cd8d2f2ecb96)
类似这样，在三个node的配置中都添加
