### ISSUE TITLE
原语平台部署图

### ISSUE THREAD

**Issue by fjibj** [primihub/primihub-platform#169]
近日预研原语平台，得到原语研发团队支持，受益颇多，非常感谢！

根据最近平台部署情况，特整理以下原语平台部署图，欢迎指正

[原语平台部署图](https://github.com/fjibj/FederatedML/blob/main/%E5%8E%9F%E8%AF%AD%E5%B9%B3%E5%8F%B0%E9%83%A8%E7%BD%B2%E5%9B%BE.jpg)

**Comment by simongong** [comment]
感谢总结和分享，我们会考虑整合到产品文档里。
