### ISSUE TITLE
webconsole编译不成功

### ISSUE THREAD

**Issue by WeC9** [primihub/primihub-platform#216]
**bug描述**

sudo npm run dev  编译不成功

<img width="747" alt="fb008f30c26fd516d4c30d2080bdfaa" src="https://github.com/primihub/primihub-platform/assets/33754233/9d90c925-f08b-4cf2-8240-b7f851458c9c">

![1698067076515](https://github.com/primihub/primihub-platform/assets/33754233/de189c1b-40bf-4dac-aa72-b7dffd78f1e6)

![image](https://github.com/primihub/primihub-platform/assets/33754233/ff42b4d6-abc2-44eb-b104-9096f2703215)

**复现步骤**

1、cd primihub-webconsole
2、sudo npm install
3、target: 'your gateway url',  (使用  route -n  命令查到的）
4、sudo npm run dev

按照文档操作出现的
https://docs.primihub.com/docs/developer-docs/platform/#%E6%8E%A7%E5%88%B6%E5%8F%B0
**bug日志**

**环境（请填写完整）:**

- OS:       ubuntu20,04
- Arch:    arm64
- 部署方式:     本机编译
- PrimiHub版本: primihub-platform 于2023/10/23
- npm版本:   6.14.18 (版本降至6.10也会）

**Comment by Zjj614** [comment]
npm包未安装正确

npm版本及node版本参考
<img width="462" alt="image" src="https://github.com/primihub/primihub-platform/assets/107016099/acd67bbf-2a17-4aee-a6fb-ac27e8a86c7e">

清一下缓存，在终端输入： npm cache clear --force
删掉node_modules包，重新npm install 安装
