### ISSUE TITLE
本地编译启动的那个端口号是什么意思，是相当于后端启动了吗？

### ISSUE THREAD

**Issue by Handikang** [primihub/primihub-platform#222]
![image](https://github.com/primihub/primihub-platform/assets/42713276/3bb31eff-8a3e-46f1-8630-4c6d8413129e)
这个端口是什么意思，还有咱们提供新增组件的流程吗，还有前端代码是不是就在primihub/primihub-platform/primihub-webconsole,后端代码在primihub/primihub-platform/primihub-service

**Comment by fuxingbit** [comment]
https://docs.primihub.com/docs/developer-docs/platform ,看一下平台的架构，端口代表启动了隐私计算节点node，代码位置你说的是对的

**Comment by Handikang** [comment]
好的，感谢
