### ISSUE TITLE
部署好了平台之后发现导入数据库类型源失败，提示链接url有问题，但是用navicat是可以连接上的

### ISSUE THREAD

**Issue by Handikang** [primihub/primihub-platform#223]
![image](https://github.com/primihub/primihub-platform/assets/42713276/bd957b42-41ff-489a-9634-71f5c35572e3)

**Comment by fuxingbit** [comment]
不要用127的地址，换成你机器的IP，127的地址在docker里不行

**Comment by Handikang** [comment]
好的，感谢

**Comment by Handikang** [comment]
![image](https://github.com/primihub/primihub-platform/assets/42713276/ab260344-22cb-4d5d-a498-2b2886d66dbc)
@fuxingbit  选中了数据源之后显示请求异常是为什么呀

**Comment by fuxingbit** [comment]
看下日志
