### ISSUE TITLE
启动primihub-meta服务的时候报错

### ISSUE THREAD

**Issue by Handikang** [primihub/primihub-platform#224]
![image](https://github.com/primihub/primihub-platform/assets/42713276/ff8c669b-a9d8-420f-a168-3fa47dbfd484)
希望大神看看这是什么问题

**Comment by likehabits** [comment]
请检查 nacos 命名空间下配置中心是否有fusion.yaml 配置文件。fusion.yaml文件实例在meta工程下script目录下
