### ISSUE TITLE
Invalid container image name from primihub-service

### ISSUE THREAD

**Issue by LinuxSuRen** [primihub/primihub-platform#35]
```shell
docker pull java:8-jre
Error response from daemon: manifest for java:8-jre not found: manifest unknown: manifest unknown
```

See also https://github.com/primihub/primihub-platform/blob/4eed1fb9ec0cc9252aa54c154cd863abf738957c/primihub-service/Dockerfile.local#L10

I suggest that we use the same base image `ibmjava:8-jre` with 
https://github.com/primihub/primihub-platform/blob/4eed1fb9ec0cc9252aa54c154cd863abf738957c/primihub-service/Dockerfile#L1

**Comment by LinuxSuRen** [comment]
By the way, `ibmjava:8-jre` does not support `arm64`. It cannot work for those users who are using macOS m1. We might need to switch the base image to an appropriate one. Such as `openjdk:8-jre-alpine3.8`

**Comment by fuxingbit** [comment]
Thanks, this is indeed a bug and it has been fixed.
