### ISSUE TITLE
Unable to perform inference task.

### ISSUE THREAD

**Issue by 271983592** [primihub/primihub-platform#77]
Hi, all
    I used 1.5.0 for a few days. I have trained a homo-lr model and I wanted to make an inference task.
    But I found I could not selected test data on the UI. I studied the service code (primihub-service) and found it get resource information from local db (not from fusion db). 
    I also found there was no infer codes (*fbl) for hetero-xgb in "templates" path of primihub-service.  Can the platform now do the inference task for hetero-xgb?

Thanks for your job and looking forward to your reply.

**Comment by likehabits** [comment]
About homo lr reasoning, local data is mainly selected for back-end discovery services.
Please wait patiently for the hetero xgb model. We will integrate and release it as soon as possible.

**Comment by 271983592** [comment]
I got it. Look forward to your greate work.
In addition, I found it seems that the verification step is not added at the end of model training.
